image: docker:20-git
services:
  - docker:20-dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - lint
  - build
  - package

lint:
  stage: lint
  image: python:3.10-bookworm
  script:
    - pip install pylint
    - pip install --no-cache-dir -r requirements.txt
    - pylint download_models.py
    - pylint app/**/*.py

docker-build:
  stage: package
  only:
    - main
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest -t $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8} -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}